version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333" # Port pour l'API REST (crucial pour notre script Python)
      - "6334:6334" # Port pour l'API gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always